# Generated by Django 5.1.2 on 2024-10-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('Running', 'Running'), ('Cycling', 'Cycling'), ('Swimming', 'Swimming')], max_length=50),
        ),
    ]
